Enable parsing of loaded Dataframes. Improve function naming.
oncodash/ontoweaver pull request #82
Opened 2024-12-19 10:19 UTC by mbaric758

- After merging usages of `extract` and `tabular.extract_all` functions should be renamed in OncodashKB.

2025-01-13 09:05 UTC, jdreo requested changes
A nice feature, but as far as I understood the code, the implementation for using in-memory dataframes is missing? It should be very simple to fix, though.

2025-01-13 09:05 UTC, jdreo commented on src/ontoweaver/__init__.py
> +    if loaded_data_mappings:
I think there is a mistake in this section. The docstring says that this should handle dataframes already loaded in memory by the caller, but the code is the same than the `data_mappings` section. This looks like a test code that was forgotten. The code should probably just be the call to `extract_table` ? And then you may use a single call to `nodes += adapter.nodes` for both sections.

2025-01-13 09:05 UTC, jdreo commented on src/ontoweaver/__init__.py
> +    if loaded_data_mappings:
Same comment than for line 65 here.

2025-01-13 09:05 UTC, jdreo commented on src/ontoweaver/__init__.py
> +def extract_reconciliate_write(biocypher_config_path, schema_path, data_mappings = None, loaded_data_mappings = None, parallel_mapping = 0, separator = None, affix = "none", affix_separator = ":"):
I feel the names of the data => mapping dictionaries are not the clearest. What about those:
```suggestion
def extract_reconciliate_write(biocypher_config_path, schema_path, filename_to_mapping = None, dataframe_to_mapping = None, parallel_mapping = 0, separator = None, affix = "none", affix_separator = ":"):
```

2025-01-13 14:19 UTC, jdreo commented on src/ontoweaver/__init__.py
> +    if loaded_data_mappings:
Yes, I think the best option is to let the user manage the loading. So pass a "dataframe => yaml object" dictionary, and do not play with loading. So that we have two clear options: 1) you just pass filenames, 2) you pass loaded objects.

2025-01-13 14:43 UTC, mbaric758 commented on src/ontoweaver/__init__.py
> +    if loaded_data_mappings:
About the single call to `nodes += adapter.nodes` for both sections, I thought about keeping the option for a use case of wanting to pass both in memory objects and file paths to the function? In that case we would need both branches to have their own `nodes += adapter.nodes` and `edges += adapter.edges`, but if this is not a plausible case I can also change it to a single appending for both. What do you think?

2025-01-13 16:15 UTC, jdreo commented on src/ontoweaver/__init__.py
> +    if loaded_data_mappings:
I find that this would be a bit confusing to have too many options.

If I am completely rigorous, I would say that the low-level implementation of an Adapter should only take loaded in-memory objects, and the user should be in charge of preparing them with whatever method they prefer (loading from a file should be simple enough for any programmer, and that opens the way to load from strings that come from the network, named pipes or whatever automated process). This would work perfectly fine with a user loading an input from a file, and a mapping from somewhere else.

Now, I also agree that some user might still have a hard time to think of anything else than files (I keep seeing that in the bioinformatics world, so maybe there's a thing here). My favorite way of handling that would be to have a *separated* proxy adapter, which would take filenames and not objects, and then just call the actual adapter doing the job.

2025-01-15 13:59 UTC, jdreo requested changes
Good enough, but I made an error on asking for elements accumulation in a separate section.

2025-01-15 13:59 UTC, jdreo commented on src/ontoweaver/__init__.py
> +                                            separator=affix_separator)
This is going to overwrite the adapter object, and not accumulate the nodes. This is my fault with this bad idea of putting the node accumulation in a later section. Sorry.

2025-01-24 13:38 UTC, jdreo requested changes
Almost good to go! Just a few mistakes & nitpicking in the doc.

2025-01-24 13:38 UTC, jdreo commented on docs/README.rst
> +   ontoweave --config biocypher_config.yaml --schema schema_config.yaml data-1.1.csv:map-1.yaml data-1.2.csv:map-1.yaml data-A.csv:map-A.yaml
```suggestion
   ontoweave --biocypher-config biocypher_config.yaml --biocypher-schema schema_config.yaml data-1.1.csv:map-1.yaml data-1.2.csv:map-1.yaml data-A.csv:map-A.yaml
```

2025-01-24 13:38 UTC, jdreo commented on docs/readme_sections/overview.rst
> +|image1|
```suggestion
|OntoWeaver logo|
```

2025-01-24 13:38 UTC, jdreo commented on docs/readme_sections/overview.rst
> +.. |image1| image:: docs/OntoWeaver_logo__big.svg
```suggestion
.. |OntoWeaver logo| image:: docs/OntoWeaver_logo__big.svg
```

2025-01-24 13:38 UTC, jdreo commented on docs/readme_sections/usage.rst
> +   ontoweave --config biocypher_config.yaml --schema schema_config.yaml data-1.1.csv:map-1.yaml data-1.2.csv:map-1.yaml data-A.csv:map-A.yaml
```suggestion
   ontoweave --biocypher-config biocypher_config.yaml --biocypher-schema schema_config.yaml data-1.1.csv:map-1.yaml data-1.2.csv:map-1.yaml data-A.csv:map-A.yaml
```

2025-01-27 16:29 UTC, merged